### ISSUE TITLE
HTTP POST fails

### ISSUE THREAD

**Issue by mslinn** [jdegoes/blueeyes#29]
Given this CURL POST:

```
curl -sSv --header Content-Type:application/json --data-urlencode 'document=Of course you realize that this means war' http://localhost:8585/json/blah/78e68fde-3995-4a35-bdc7-8746c6a2e47b
```

with this response:

```
* About to connect() to localhost port 8585 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8585 (#0)
> POST /json/blah/7672be51-88d3-4b86-b69d-fc72cfbbf64e HTTP/1.1
> User-Agent: curl/7.21.6 (x86_64-pc-linux-gnu) libcurl/7.21.6 OpenSSL/1.0.0e zlib/1.2.3.4 libidn/1.22 librtmp/2.3
> Host: localhost:8585
> Accept: */*
> Content-Type:application/json
> Content-Length: 64
> 
} [data not shown]
< HTTP/1.1 500 There was an internal server error.
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection #0
```

I get the following error message:

```
ERR [20111022-12:40:39.053] blueeyes: Error handling request
ERR [20111022-12:40:39.053] blueeyes: blueeyes.json.JsonParser$ParseException: Data is too big, use big data handler. If "aggregate" combinator is used then probably Json is broken.
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.BijectionsChunkJson$$anon$1.unapply(BijectionsChunkJson.scala:23)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.BijectionsChunkJson$$anon$1.unapply(BijectionsChunkJson.scala:11)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.Bijection$$anon$1.apply(Bijection.scala:20)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10$$anonfun$apply$10.apply(HttpRequestHandlerCombinators.scala:347)
ERR [20111022-12:40:39.053] blueeyes:     at scala.Option.map(Option.scala:133)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10.apply(HttpRequestHandlerCombinators.scala:347)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10.apply(HttpRequestHandlerCombinators.scala:331)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anonfun$path$1$$anon$1.apply(HttpRequestHandlerCombinators.scala:36)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anonfun$path$1$$anon$1.apply(HttpRequestHandlerCombinators.scala:28)
ERR [20111022-12:40:39.053] blueeyes:     at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:46)
ERR [20111022-12:40:39.053] blueeyes:     at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:45)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpServer$class.apply(HttpServer.scala:68)
ERR [20111022-12:40:39.053] blueeyes:     at net.interdoodle.hbe.AppServer$.apply(AppServer.scala:7)
ERR [20111022-12:40:39.053] blueeyes:     at net.interdoodle.hbe.AppServer$.apply(AppServer.scala:7)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyRequestHandler.messageReceived(NettyRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler$$anonfun$messageReceived$1.apply(NettyChunkedRequestHandler.scala:58)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler$$anonfun$messageReceived$1.apply(NettyChunkedRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at scala.Option.foreach(Option.scala:197)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler.messageReceived(NettyChunkedRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:148)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
ERR [20111022-12:40:39.053] blueeyes:     (...more...)
ERR [20111022-12:40:39.053] blueeyes: Caused by blueeyes.json.JsonParser$ParseException: unknown token d
Near: document=Of%20course%
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$Parser.fail(JsonParser.scala:230)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$Parser.nextToken(JsonParser.scala:325)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$$anonfun$4.apply(JsonParser.scala:188)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$$anonfun$4.apply(JsonParser.scala:142)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$.parse(JsonParser.scala:75)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.json.JsonParser$.parse(JsonParser.scala:51)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.BijectionsChunkJson$$anon$1.unapply(BijectionsChunkJson.scala:21)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.BijectionsChunkJson$$anon$1.unapply(BijectionsChunkJson.scala:11)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.data.Bijection$$anon$1.apply(Bijection.scala:20)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10$$anonfun$apply$10.apply(HttpRequestHandlerCombinators.scala:347)
ERR [20111022-12:40:39.053] blueeyes:     at scala.Option.map(Option.scala:133)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10.apply(HttpRequestHandlerCombinators.scala:347)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anon$10.apply(HttpRequestHandlerCombinators.scala:331)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anonfun$path$1$$anon$1.apply(HttpRequestHandlerCombinators.scala:36)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpRequestHandlerCombinators$$anonfun$path$1$$anon$1.apply(HttpRequestHandlerCombinators.scala:28)
ERR [20111022-12:40:39.053] blueeyes:     at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:46)
ERR [20111022-12:40:39.053] blueeyes:     at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:45)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.HttpServer$class.apply(HttpServer.scala:68)
ERR [20111022-12:40:39.053] blueeyes:     at net.interdoodle.hbe.AppServer$.apply(AppServer.scala:7)
ERR [20111022-12:40:39.053] blueeyes:     at net.interdoodle.hbe.AppServer$.apply(AppServer.scala:7)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyRequestHandler.messageReceived(NettyRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler$$anonfun$messageReceived$1.apply(NettyChunkedRequestHandler.scala:58)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler$$anonfun$messageReceived$1.apply(NettyChunkedRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at scala.Option.foreach(Option.scala:197)
ERR [20111022-12:40:39.053] blueeyes:     at blueeyes.core.service.engines.NettyChunkedRequestHandler.messageReceived(NettyChunkedRequestHandler.scala:43)
ERR [20111022-12:40:39.053] blueeyes:     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
ERR [20111022-12:40:39.053] blueeyes:     (...more...)
```

from the following JsonService trait:

```
package net.interdoodle.hbe

import blueeyes._
import blueeyes.concurrent.Future
import blueeyes.core.data.{BijectionsChunkJson, BijectionsChunkString, ByteChunk}
import blueeyes.core.http.{HttpRequest, HttpResponse, HttpStatus}
import blueeyes.core.http.{HttpCookie, HttpDateTime}
import blueeyes.core.http.combinators.HttpRequestCombinators
import blueeyes.core.service.{HttpService, HttpServiceContext}
import blueeyes.json.JsonAST._
import net.interdoodle.hbe.domain.Hanuman
import scala.collection.mutable.HashMap
import java.util.UUID


  trait HelloJsonServices extends BlueEyesServiceBuilder
    with HttpRequestCombinators
    with BijectionsChunkString
    with BijectionsChunkJson {

  val sessions = new HashMap[String, Some[Hanuman]]()

  val helloJson: HttpService[ByteChunk] = service("helloJson", "0.1") {
    requestLogging {
      logging {
        log =>
          context: HttpServiceContext =>
            request {
              path("/json/") {
                jvalue {
                  get {
                    requestParam:HttpRequest[JValue] =>
                      val json = JString("Hello World!")
                      val response = HttpResponse[JValue](content = Some(json))
                      log.info(response.toString())
                      Future.sync(response)
                  } ~
                  path('operation) {
                    get { request =>
                      val operation = request.parameters('operation)
                      if (operation=="newSession") {
                        val sessionID = UUID.randomUUID().toString
                        sessions += sessionID -> Some(null)
                        Future.sync(HttpResponse(
                          /*headers = HttpHeaders.Empty + sessionCookie(sessionID),*/
                          content = Some(sessionID)))
                      } else {
                        val msg = "The only operation that can be without a sessionID is newSession. You specified '" + operation + "'"
                        Future.sync(HttpResponse(status=HttpStatus(400, msg),
                                                 content = Some(msg)))
                      }
                    }
                  } ~
                  path('operation/'id) {
                    post { request =>
                      val operation = request.parameters('operation)
                      val sessionID = request.parameters('id)
                      val session = sessions.getOrElse(sessionID, None)
                      Future.sync(HttpResponse(
                        /*headers = HttpHeaders.Empty + sessionCookie(sessionID),*/
                        content = if (session==null)
                          Some("Session with ID " + sessionID + " does not exist")
                        else
                          Some("session ID=" + sessionID + "; operation: '" + operation + "'"))
                      )
                    }
                  } ~
                  path('operation/'id/'param) {
                    post { request =>
                      val operation = request.parameters('operation)
                      val sessionID = request.parameters('id)
                      val param = request.parameters('param)
                      val session = sessions.getOrElse(sessionID, None)
                      Future.sync(HttpResponse(
                        /*headers = HttpHeaders.Empty + sessionCookie(sessionID),*/
                        content = if (session==null)
                          Some("Session with ID " + sessionID + " does not exist")
                        else
                          Some("session ID=" + sessionID + "; operation: '" + operation + "'"))
                      )
                    }
                  }
                }
              }
            }
      }
    }
  }
}
```

The error does not manifest with an HTTP GET, when the service is modified for get instead of post.

**Comment by jdegoes** [comment]
This happens because the data you are posing to the service is not valid JSON. If you want to handle key/value pairs, then you should do so "outside" the jvalue combinator (which forces request/response to be JSON).

**Comment by mslinn** [comment]
Thanks, of course it is obvious now that you mention it! 

Maybe there could be a more graceful response than an HTTP status 500?

Thanks again for your kind assistance.

**Comment by mslinn** [comment]
This is not legal, but is there a way to do something similar?

```
  val helloJson: HttpService[ByteChunk] = service("helloJson", "0.1") {
    requestLogging {
      logging {
        log =>
          context: HttpServiceContext =>
            request {
              path("/upload") {
                produce(text/html) { post { request => reqDocument(log, request) } }
              } ~
              path("/json/") {
                jvalue {
                  get { requestParam:HttpRequest[JValue] => reqHello(log) } ~
                  path('operation) {
                    get { request => reqOperation(log, request) }
                  } ~
                  path('operation/'id) {
                    get { request => reqDoCommand(log, request) }
                  } ~
                  path('operation/'id/'param) {
                    get { request => reqDoCommandParam(log, request) }
                  } ~
                  orFail(HttpStatusCodes.NotFound, "No handler found that could handle this request.") // return HTTP status 404
                }
              }
            }
      }
    }
  }
```

I get this error:

```
error: object HttpRequestHandlerCombinators is not a member of package blueeyes.core.service
Note: trait HttpRequestHandlerCombinators exists, but it has no companion object.
import core.service.HttpRequestHandlerCombinators._
```

**Comment by jdegoes** [comment]
Do you know which line of code is causing the problem?

**Comment by jdegoes** [comment]
The referenced error looks like you're trying to import everything in a companion object from HttpRequestHandlerCombinators, which the compiler can't find.

**Comment by mslinn** [comment]
Rewriting line 8 this way solved it:

```
produce(text/html) { post { request:HttpRequest[ByteChunk] => reqDocument(log, request) } }
```

However, the reqDocument() function finds no parameters. ( `java.util.NoSuchElementException: key not found: 'document`)

```
  private def reqDocument[T](log:Logger, request:HttpRequest[T]) = {
    val params = request.parameters
    for (kv<-params)
      log.info(kv.toString())
    try {
      val document:String = request.parameters('document)
      val response = HttpResponse[String](content = Some("Uploaded document has " + document.length + " characters"))
      Future.sync(response)
    } catch {
      case e:Exception =>
        log.info(e.toString)
        Future.sync(HttpResponse[String](content=Some(e.toString)))
    }
  }
```

... when invoked by curl this way:

```
curl -sSv --data-urlencode "sessionid=$SESSION_ID&document=Of course you realize that this means war" "http://localhost:8585/upload"
```

Same result when invoked from this web page:

```
<form method=post action="http://localhost:8585/upload">
    <input type=hidden name=sessionid value=bogus>
    <input type=hidden name=document value="Of course you realize that this means war">
    <input type=submit>
</form>
```

**Comment by jdegoes** [comment]
HttpRequest.parameters will only contain symbols or named capture groups in regular expressions; right now, BlueEyes does not attempt to translate the POST body into request parameters. However, that's a good idea and one we could support quite easily with another combinator. We will add it.

**Comment by mslinn** [comment]
I'll stub out the application functionality and fake the parameter for now - even better, is there a combinator for MIME type Application/x-www-form-urlencoded?

**Comment by jdegoes** [comment]
If not, it's fairly easy to do a custom mime-type. See the MimeTypes file for information on how to do that.

**Comment by mslinn** [comment]
Actually, I should have asked about action `multipart/form-data`, and it looks like it is supported already:

```
$ git grep multipart
src/main/scala/blueeyes/core/http/MimeType.scala:    def MimeTypeRegex = new Regex("""((application)|(text)|(audio)|(multipart)|(image)|(video)|(\*))/(([a-z\-]+)|\*)""
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "mixed")            => Array(multipart / mixed)
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "alternative")    => Array(multipart / alternative)
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "related")        => Array(multipart / related)
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "form-data")      => Array(multipart / `form-data`)
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "signed")         => Array(multipart / signed)
src/main/scala/blueeyes/core/http/MimeType.scala:        case Array("multipart", "encrypted")      => Array(multipart / encrypted)
src/main/scala/blueeyes/core/http/MimeType.scala:  object multipart {
src/main/scala/blueeyes/core/http/MimeType.scala:    def / (multipartType: MultipartType) = new MimeType {
src/main/scala/blueeyes/core/http/MimeType.scala:      def maintype = "multipart"
src/main/scala/blueeyes/core/http/MimeType.scala:      def subtype = multipartType.subtype
src/main/scala/blueeyes/core/http/MimeType.scala:      override def extensions = multipartType.extensions
src/test/scala/blueeyes/core/http/MimeTypeSpec.scala:    HttpHeaders.`Content-Type`(MimeTypes.parseMimeTypes("multipart/mixed, application/*"): _*).value mustEqual "mu
```

I'll see if I can get that to work.

**Comment by mslinn** [comment]
I'm having trouble pulling out the uploaded data sent from this HTML form:

```
<form method=post  enctype='multipart/form-data' action="http://localhost:8585/upload">
    <input type=hidden name=sessionid value=bogus>
    <input type=file name=document>
    <input type=submit>
</form>
```

...with the following code:

```
  path("/upload") {
    produce(multipart/`form-data`) { post { request:HttpRequest[ByteChunk] => reqDocument(log, request) } }
  }

...

 private def reqDocument[T](log:Logger, request:HttpRequest[T]) = {
    try {
      log.info(request.content.toString)
      val data = MemoryChunk(request.content) // The debugger shows me a MemoryChunk in request.content
  }
```

How can I pull out the value of the MemoryChunk?

BTW, the `sessionid` parameter from the form does not seem to appear in the data. Not a problem for this use case, but name/value pairs are often specified with `multipart/form-data` so this might be a problem for someone else

**Comment by jdegoes** [comment]
Hi Mike,

I'm CC'ing Misha who will be able to help you on this one (I've not done this before).

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes
